# Generated by Django 3.2 on 2021-06-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.IntegerField()),
            ],
        ),
    ]
