# Generated by Django 3.2 on 2021-06-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=10)),
                ('mot_passe', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('dateN', models.DateField(null=True)),
                ('nbr_femmes', models.IntegerField()),
                ('num_inférentiek_inf', models.IntegerField()),
                ('situation_familiale', models.CharField(max_length=50)),
                ('categorie', models.IntegerField()),
                ('rang', models.IntegerField()),
                ('nbr_enfants', models.IntegerField()),
                ('num_telephon', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=10)),
                ('Nommarital', models.CharField(max_length=50)),
                ('Date_de_recrutement', models.DateField(null=True)),
                ('postes', models.CharField(max_length=500)),
            ],
        ),
    ]
